### PR TITLE
[CMSP-482] Fix "composer update --dry-run"

### PR DESCRIPTION
**Pull request by greg-1-anderson**
See https://github.com/pantheon-systems/drupal-composer-managed/pull/39

### CODE REVIEW

**Comment by greg-1-anderson** [comment]
I didn't notice that we have pantheon-systems/wordpress-composer-managed. Perhaps I was thinking of the older wordpress-project, which only existed in the pantheon-upstreams project.

**Comment by greg-1-anderson** [comment]
This needs to be combined with https://github.com/pantheon-systems/wordpress-composer-managed/pull/105 anyway.

**Comment by jazzsequence** [comment]
@greg-1-anderson I'm not sure what to do with this PR. Are you saying that the changes made here should be part of that PR? Why close with unmerged commits?

**Comment by jazzsequence** [comment]
oh, right, this is `pantheon-upstreams`

**Pull request closed without merging**
